package view;

import controller.ControladorTelaJogo;

public class Jogo extends javax.swing.JFrame {
    ControladorTelaJogo controlador;
    private Boolean botaoApertado;
    private final Object lockerObject = new Object();
    
    public Jogo(ControladorTelaJogo ctr) {
        botaoApertado = false;
        initComponents();
        controlador = ctr; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_desistir = new javax.swing.JButton();
        btn_frente = new javax.swing.JButton();
        btn_tras = new javax.swing.JButton();
        btn_direita = new javax.swing.JButton();
        btn_esquerda = new javax.swing.JButton();
        jpn_game = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snake - Partida");

        btn_desistir.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        btn_desistir.setText("Desistir");
        btn_desistir.setName("btn_desistir"); // NOI18N
        btn_desistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desistirActionPerformed(evt);
            }
        });

        btn_frente.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_frente.setText("↑");
        btn_frente.setAlignmentY(0.0F);
        btn_frente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_frente.setName("btn_frente"); // NOI18N
        btn_frente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frenteActionPerformed(evt);
            }
        });

        btn_tras.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_tras.setText("↓");
        btn_tras.setAlignmentY(0.0F);
        btn_tras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tras.setName("btn_tras"); // NOI18N
        btn_tras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trasActionPerformed(evt);
            }
        });

        btn_direita.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_direita.setText("→");
        btn_direita.setAlignmentY(0.0F);
        btn_direita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_direita.setName("btn_direita"); // NOI18N
        btn_direita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_direitaActionPerformed(evt);
            }
        });

        btn_esquerda.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_esquerda.setText("←");
        btn_esquerda.setAlignmentY(0.0F);
        btn_esquerda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_esquerda.setName("btn_esquerda"); // NOI18N
        btn_esquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_esquerdaActionPerformed(evt);
            }
        });

        jpn_game.setName("jpn_game"); // NOI18N
        jpn_game.setPreferredSize(new java.awt.Dimension(1000, 500));

        javax.swing.GroupLayout jpn_gameLayout = new javax.swing.GroupLayout(jpn_game);
        jpn_game.setLayout(jpn_gameLayout);
        jpn_gameLayout.setHorizontalGroup(
            jpn_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jpn_gameLayout.setVerticalGroup(
            jpn_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        lbl_titulo.setFont(new java.awt.Font("Consolas", 1, 68)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("Snake");

        lbl_nome.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lbl_nome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nome.setText("Olá, jogador!");
        lbl_nome.setName("lbl_nome"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpn_game, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_frente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_esquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_tras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_direita, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_desistir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpn_game, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_desistir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_frente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_direita, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_esquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_desistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desistirActionPerformed
        synchronized(lockerObject){
            if(!botaoApertado){
                botaoApertado = true;
                controlador.desistir();
            }
        }
    }//GEN-LAST:event_btn_desistirActionPerformed

    private void btn_frenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frenteActionPerformed
        controlador.up();
    }//GEN-LAST:event_btn_frenteActionPerformed

    private void btn_trasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trasActionPerformed
        controlador.down();
    }//GEN-LAST:event_btn_trasActionPerformed

    private void btn_esquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_esquerdaActionPerformed
        controlador.left();
    }//GEN-LAST:event_btn_esquerdaActionPerformed

    private void btn_direitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_direitaActionPerformed
        controlador.right();
    }//GEN-LAST:event_btn_direitaActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_desistir;
    private javax.swing.JButton btn_direita;
    private javax.swing.JButton btn_esquerda;
    private javax.swing.JButton btn_frente;
    private javax.swing.JButton btn_tras;
    private javax.swing.JPanel jpn_game;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
